#!/bin/bash -f

DISPLAY_MANAGER=$1


#######################################
# support function to simplify repetitive task,
# used to build up displaty path of supported modules
#
# usage::
#
#    addModule ENVIRONMENT_VARIABLE DISPLAY_TYPE [SUBDIRECTORY]
#
# TMP is a temporary display path
# TMP is internal to this script, no need to export.

function addModule
{
    # $1 is a symbol defined in <synApps>/configure/RELEASE
    # module_path is the path defined for that symbol in the RELEASE file
    module='$'$1
    module_path=`eval echo $module`

	if [ "$2" != "${DISPLAY_MANAGER}" ]; then
		return 0
	fi
	
    if [ "" != "${module}" ]; then
        # module is required
        addition=${module_path}
        if [ "" != "$3" ]; then
            # optional subdirectory path
            addition+=/$3
        fi
        if [ -d "${addition}" ]; then
            # proceed ONLY if new addition path exists
            # Then, can define paths to all area detectors specific screens
            if [ "" == "${TMP}" ]; then
                # no existing path defined, start here
                TMP=.
            fi
            TMP+=:${addition}
        fi
    fi
}


#######################################
# get environment variables for support modules 

SUPPORT=/opt/epics/synApps_5_7/support

#/usr/local/iocapps/cvsroot/modules/bus/allenBradley
ALLEN_BRADLEY=${SUPPORT}/allenBradley-2-2
AREA_DETECTOR=${SUPPORT}/areaDetector-1-9-1
#https://svn.aps.anl.gov/epics/asyn/
ASYN=${SUPPORT}/asyn-4-21
AUTOSAVE=${SUPPORT}/autosave-5-1
BUSY=${SUPPORT}/busy-1-6
CALC=${SUPPORT}/calc-3-2
CAMAC=${SUPPORT}/camac-2-7
DAC128V=${SUPPORT}/dac128V-2-7
DELAYGEN=${SUPPORT}/delaygen-1-1-0
#http://www.slac.stanford.edu/grp/cd/soft/epics/site/devIocStats/
DEVIOCSTATS=${SUPPORT}/devIocStats-3-1-7
DXP=${SUPPORT}/dxp-3-2
IP=${SUPPORT}/ip-2-14
IP330=${SUPPORT}/ip330-2-7
#https://svn.aps.anl.gov/epics/ipac/
#IPAC=${SUPPORT}/ipac-2-11
# (V2-12? have outstanding commits since V2-11)
IPAC=${SUPPORT}/ipac-2-12
IPUNIDIG=${SUPPORT}/ipUnidig-2-9
LOVE=${SUPPORT}/love-3-2-5
MCA=${SUPPORT}/mca-7-4
MEASCOMP=${SUPPORT}/measComp-1-0
MODBUS=${SUPPORT}/modbus-2-4
MOTOR=${SUPPORT}/motor-6-8
OPTICS=${SUPPORT}/optics-2-9-1
QUADEM=${SUPPORT}/quadEM-4-0
#http://www-csr.bessy.de/control/SoftDist/sequencer
SNCSEQ=${SUPPORT}/seq-2-1-13
SOFTGLUE=${SUPPORT}/softGlue-2-3
SSCAN=${SUPPORT}/sscan-2-9
STD=${SUPPORT}/std-3-2
#http://epics.web.psi.ch/software/streamdevice/
STREAM=${SUPPORT}/stream-2-6
VAC=${SUPPORT}/vac-1-4-1
VME=${SUPPORT}/vme-2-8-1
XXX=${SUPPORT}/xxx-5-7-1

CURRENT_DIR=$(pwd)


# ========  ================     ===============          ===========================
# function  MODULE_VARIABLE      Display Manager          subdirectory with .ui files
# ========  ================     ===============          ===========================
addModule   CURRENT_DIR          medm                     
addModule   CURRENT_DIR          caqtdm                   
addModule   CURRENT_DIR          caqtdm                   /autoconvert

addModule   ALIVE                medm                     /aliveApp/op/adl
addModule   ALIVE                caqtdm                   /aliveApp/op/ui
addModule   ALIVE                caqtdm                   /aliveApp/op/ui/autoconvert

addModule   AREA_DETECTOR        medm                     /ADCore/ADApp/op/adl
addModule   AREA_DETECTOR        caqtdm                   /ADCore/ADApp/op/ui
addModule   AREA_DETECTOR        caqtdm                   /ADCore/ADApp/op/ui/autoconvert

addModule   ADSIMDETECTOR        medm                     /simDetectorApp/op/adl
addModule   ADSIMDETECTOR        caqtdm                   /simDetectorApp/op/ui
addModule   ADSIMDETECTOR        caqtdm                   /simDetectorApp/op/ui/autoconvert

addModule   ADURL                medm                     /urlApp/op/adl
addModule   ADURL                caqtdm                   /urlApp/op/ui
addModule   ADURL                caqtdm                   /urlApp/op/ui/autoconvert

addModule   ASYN                 medm                     /opi/medm
addModule   ASYN                 caqtdm                   /opi/caqtdm
addModule   ASYN                 caqtdm                   /opi/caqtdm/autoconvert

addModule   AUTOSAVE             medm                     /asApp/op/adl
addModule   AUTOSAVE             caqtdm                   /asApp/op/ui
addModule   AUTOSAVE             caqtdm                   /asApp/op/ui/autoconvert

addModule   BUSY                 medm                     /busyApp/op/adl
addModule   BUSY                 caqtdm                   /busyApp/op/ui
addModule   BUSY                 caqtdm                   /busyApp/op/ui/autoconvert

addModule   CALC                 medm                     /calcApp/op/adl
addModule   CALC                 caqtdm                   /calcApp/op/ui
addModule   CALC                 caqtdm                   /calcApp/op/ui/autoconvert

addModule   CAMAC                medm                     /camacApp/op/adl
addModule   CAMAC                caqtdm                   /camacApp/op/ui
addModule   CAMAC                caqtdm                   /camacApp/op/ui/autoconvert

addModule   CAPUTRECORDER        medm                     /caputRecorderApp/op/adl
addModule   CAPUTRECORDER        caqtdm                   /caputRecorderApp/op/ui
addModule   CAPUTRECORDER        caqtdm                   /caputRecorderApp/op/ui/autoconvert

addModule   DAC128V              medm                     /dac128VApp/op/adl
addModule   DAC128V              caqtdm                   /dac128VApp/op/ui
addModule   DAC128V              caqtdm                   /dac128VApp/op/ui/autoconvert

addModule   DELAYGEN             medm                     /delaygenApp/op/adl
addModule   DELAYGEN             caqtdm                   /delaygenApp/op/ui
addModule   DELAYGEN             caqtdm                   /delaygenApp/op/ui/autoconvert

addModule   DXP                  medm                     /dxpApp/op/ui
addModule   DXP                  caqtdm                   /dxpApp/op/ui
addModule   DXP                  caqtdm                   /dxpApp/op/ui/autoconvert

addModule   DXPSITORO            medm                     /dxpSITOROApp/op/adl
addModule   DXPSITORO            caqtdm                   /dxpSITOROApp/op/ui
addModule   DXPSITORO            caqtdm                   /dxpSITOROApp/op/ui/autoconvert

addModule   DEVIOCSTATS          medm                     /op/adl
addModule   DEVIOCSTATS          caqtdm                   /op/ui
addModule   DEVIOCSTATS          caqtdm                   /op/ui/autoconvert

addModule   FLY                  medm                     /flyApp/op/adl
addModule   FLY                  caqtdm                   /flyApp/op/ui
addModule   FLY                  caqtdm                   /flyApp/op/ui/autoconvert

addModule   IP                   medm                     /ipApp/op/adl
addModule   IP                   caqtdm                   /ipApp/op/ui
addModule   IP                   caqtdm                   /ipApp/op/ui/autoconvert

addModule   IP330                medm                     /ip330App/op/adl
addModule   IP330                caqtdm                   /ip330App/op/ui
addModule   IP330                caqtdm                   /ip330App/op/ui/autoconvert

addModule   IPUNIDIG             medm                     /ipUnidigApp/op/adl
addModule   IPUNIDIG             caqtdm                   /ipUnidigApp/op/ui
addModule   IPUNIDIG             caqtdm                   /ipUnidigApp/op/ui/autoconvert

addModule   LOVE                 medm                     /loveApp/op/adl
addModule   LOVE                 caqtdm                   /loveApp/op/ui
addModule   LOVE                 caqtdm                   /loveApp/op/ui/autoconvert

addModule   LUA                  medm                     /luaApp/op/adl
addModule   LUA                  caqtdm                   /luaApp/op/ui
addModule   LUA                  caqtdm                   /luaApp/op/ui/autoconvert

addModule   MCA                  medm                     /mcaApp/op/adl
addModule   MCA                  caqtdm                   /mcaApp/op/ui
addModule   MCA                  caqtdm                   /mcaApp/op/ui/autoconvert

addModule   MODBUS               medm                     /modbusApp/op/adl
addModule   MODBUS               caqtdm                   /modbusApp/op/ui
addModule   MODBUS               caqtdm                   /modbusApp/op/ui/autoconvert

addModule   MOTOR                medm                     /motorApp/op/adl
addModule   MOTOR                caqtdm                   /motorApp/op/ui
addModule   MOTOR                caqtdm                   /motorApp/op/ui/autoconvert

addModule   OPTICS               medm                     /opticsApp/op/adl
addModule   OPTICS               caqtdm                   /opticsApp/op/ui
addModule   OPTICS               caqtdm                   /opticsApp/op/ui/autoconvert

addModule   QUADEM               medm                     /quadEMApp/op/adl
addModule   QUADEM               caqtdm                   /quadEMApp/op/ui
addModule   QUADEM               caqtdm                   /quadEMApp/op/ui/autoconvert

addModule   SOFTGLUE             medm                     /softGlueApp/op/adl
addModule   SOFTGLUE             caqtdm                   /softGlueApp/op/ui
addModule   SOFTGLUE             caqtdm                   /softGlueApp/op/ui/autoconvert

addModule   SSCAN                medm                     /sscanApp/op/adl
addModule   SSCAN                caqtdm                   /sscanApp/op/ui
addModule   SSCAN                caqtdm                   /sscanApp/op/ui/autoconvert

addModule   STD                  medm                     /stdApp/op/adl
addModule   STD                  caqtdm                   /stdApp/op/ui
addModule   STD                  caqtdm                   /stdApp/op/ui/autoconvert

addModule   TDS3000              medm                     /medm

addModule   VAC                  medm                     /vacApp/op/adl
addModule   VAC                  caqtdm                   /vacApp/op/ui
addModule   VAC                  caqtdm                   /vacApp/op/ui/autoconvert

addModule   VME                  medm                     /vmeApp/op/adl
addModule   VME                  caqtdm                   /vmeApp/op/ui
addModule   VME                  caqtdm                   /vmeApp/op/ui/autoconvert

addModule   YOKOGAWA_DAU         medm                     /mw100App/op/adl
addModule   YOKOGAWA_DAU         caqtdm                   /mw100App/op/ui
addModule   YOKOGAWA_DAU         caqtdm                   /mw100App/op/ui/autoconvert

# ========  ================  ===========================

if [ "$DISPLAY_MANAGER" == "medm" ]; then
	if [ -z "$EPICS_DISPLAY_PATH" ]; then
		export EPICS_DISPLAY_PATH=${TMP}
	else
		export EPICS_DISPLAY_PATH=${TMP}:${EPICS_DISPLAY_PATH}
	fi
fi

if [ "$DISPLAY_MANAGER" == "caqtdm" ]; then
	if [ -z "$CAQTDM_DISPLAY_PATH" ]; then
		export CAQTDM_DISPLAY_PATH=${TMP}
	else
		export CAQTDM_DISPLAY_PATH=${TMP}:${CAQTDM_DISPLAY_PATH}
	fi
fi
